// File generated by FlutterFire CLI — do not edit manually.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) return web;
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return web; // placeholder – add google-services.json for native
      case TargetPlatform.iOS:
        return web; // placeholder – add GoogleService-Info.plist for native
      default:
        return web;
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC3H4-e5dIlBPN_h3hvDEBzS0AfexsVqvw',
    authDomain: 'wealth-tracker-538f6.firebaseapp.com',
    projectId: 'wealth-tracker-538f6',
    storageBucket: 'wealth-tracker-538f6.firebasestorage.app',
    messagingSenderId: '246720050895',
    appId: '1:246720050895:web:59467acee5b31b292129ba',
    measurementId: 'G-F1PKS87LFW',
  );
}
